POST http://localhost/bbdd/contacto.php
Content-Type: application/x-www-form-urlencoded

id_contacto=12&nombre=roberto&apellidos=garzia_aparisi&mail=robertopeneabierto@gmail.com&motivo=contratoSondas&


###
